### PR TITLE
Adds .NET 4.5 as target framework.

### PR DESCRIPTION
**Pull request by ChrSteinert**
Sorry - I recon I was holding up #15.

So no here a (locally building) multi target for .NET 4.5 and .NET Standard 2.0.

### CODE REVIEW

**Comment by Eleanor68** [comment]
Are we not interested in .NET 4.5 for unit tests?

**Comment by ChrSteinert** [comment]
Dunno - I think if .NET Standard 2.0 runs, Net4.5 runs as well, no?
Happy to add it, if one of the maintainers wants to have it. @jamessdixon
@kapilash ?

**Comment by jamessdixon** [comment]
Currently, it is on nuget with .NET 4.0 as the highest version
I makes sense to

**Comment by ChrSteinert** [comment]
So target net4, net45, and netstandard2.0?

**Comment by jamessdixon** [comment]
Currently, the highest version supported is 4.0
Does it make sense to:
1) bring it to the highest 4.x version: 4.7.1
2) bring it to the latest core version: 2.0

and for any increase in major and/or minor version of 4.x, and Core, we upgrade?

**Comment by ChrSteinert** [comment]
But I cannot consume a net471 in an net 45 app, right?

**Comment by jamessdixon** [comment]
Correct.  If we wanted to support 4.5, we would need to release one specific to it.  But if I had a 4.5 app, I can always use the 4.0 one.  Unless there are some features in 4.5 that we want to take advantage of?

**Comment by jamessdixon** [comment]
MSFT calls it ".NET Core" and ".NET Standard".  We prob should match their terminology ?

**Comment by ChrSteinert** [comment]
I don't get your point?

**Comment by jamessdixon** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by Eleanor68** [comment]
What is the advantage of the .NET Core 2.0 package once the project does not use any specific features from it. Once the project is compatible with .NET 4.5 and you do not use any specific feature from .NET Core 2.0 why to drop support of .NET 4.5? You always can drop the support of the .NET 4.5 when you will need some specific features from >= .NET 4.5. So why not to allow customers with .NET 4.5 to receive updates.

**Comment by Eleanor68** [comment]
The Unit Tests executed from `dotnet test` will execute all tests on each runtime specified in the `.fsproj`. If you will decide to support .NET 4.5 will be a good idea to execute tests on each runtime (netcoreapp2.0;net45).

**Comment by ChrSteinert** [comment]
Ok.
Now we have a net45 package, a netstandard2.0 package, and test for both frameworks.
Any concerns?

**Pull request merged**
